ALTER TABLE sales_rep_refs ADD COLUMN last_event_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE company_refs ADD COLUMN last_event_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE contact_refs ADD COLUMN last_event_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE product_refs ADD COLUMN last_event_at TIMESTAMP WITH TIME ZONE;
