spring.application.name=notification-service
server.port=8081

spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.config.request-connect-timeout=1500
spring.cloud.config.request-read-timeout=3000

spring.datasource.url=jdbc:h2:file:./data/notificationdb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info,env,configprops
management.endpoint.health.show-details=always
management.info.env.enabled=true
info.app.name=${spring.application.name}
info.app.description=Microsservico de notificacoes do CRM
info.app.version=0.3.0

app.cors.allowed-origins=http://localhost:3000
app.notifications.sender-name=PB CRM Customer Service
app.notifications.sender-email=no-reply@pbcrm.local
app.notifications.dispatch.auto=true
app.notifications.dispatch.fixed-delay=5000
app.notifications.dispatch.batch-size=20
app.notifications.max-attempts=3

platform.config-source=local-file

spring.cloud.discovery.client.composite-indicator.enabled=false
