apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
spec:
  template:
    spec:
      containers:
        - name: otel-collector
          args:
            - --config=/etc/otelcol/config.yaml
            - --config=/etc/otelcol/splunk.yaml
          env:
            - name: SPLUNK_OTLP_ENDPOINT
              value: splunk-otel-collector-agent:4317
