clusterName: nexo-crm
environment: kubernetes

splunkObservability:
  metricsEnabled: true
  tracesEnabled: true

secret:
  create: false
  name: splunk-observability

agent:
  config:
    receivers:
      kubelet_stats:
        insecure_skip_verify: true
  controlPlaneMetrics:
    controllerManager:
      enabled: false
    scheduler:
      enabled: false
    proxy:
      enabled: false
