app.notifications.sender-name=PB CRM Customer Service
app.notifications.sender-email=no-reply@pbcrm.com
app.notifications.dispatch.auto=true
app.notifications.dispatch.fixed-delay=5000
app.notifications.dispatch.batch-size=20
app.notifications.max-attempts=3
